In [2]:
#Angad Singh Hoonjan
#RA2111053010021

import numpy as np

# Create a random 3x3 matrix
A = np.arange(1, 10).reshape(3, 3)

# Shuffle the random matrix
B = A.copy()
np.random.shuffle(B)

# Concatenate row-wise
concat_row = np.concatenate((A, B), axis=0)

# Concatenate column-wise
concat_column = np.concatenate((A, B), axis=1)

# Print the original matrix
print("Original Matrix:")
print(A)

# Print the shuffled matrix
print("\nShuffled Matrix:")
print(B)

# Print the concatenated matrices
print("\nConcatenated Row-wise:")
print(concat_row)

print("\nConcatenated Column-wise:")
print(concat_column)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shuffled Matrix:
[[4 5 6]
 [1 2 3]
 [7 8 9]]

Concatenated Row-wise:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [1 2 3]
 [7 8 9]]

Concatenated Column-wise:
[[1 2 3 4 5 6]
 [4 5 6 1 2 3]
 [7 8 9 7 8 9]]


In [4]:
#Angad Singh Hoonjan
#RA2111053010021

import pandas as pd

# Create two DataFrames with different columns
data1 = {'Name': ['Alice', 'Bob', 'Charlie'],
         'Age': [25, 30, 22]}
df1 = pd.DataFrame(data1)

data2 = {'Name': ['David', 'Eve', 'Frank'],
         'Country': ['USA', 'Canada', 'UK']}
df2 = pd.DataFrame(data2)

# Append the DataFrames
appended_df = pd.concat([df1, df2], ignore_index=True, sort=False)

# Print the appended DataFrame
print("Appended DataFrame:")
print(appended_df)


Appended DataFrame:
      Name   Age Country
0    Alice  25.0     NaN
1      Bob  30.0     NaN
2  Charlie  22.0     NaN
3    David   NaN     USA
4      Eve   NaN  Canada
5    Frank   NaN      UK
